version: '3.8'

services:
  elk:
    image: sebp/elk
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'
    volumes:
      - ./logstash:/etc/logstash/
      - ./elasticsearch:/usr/share/elasticsearch/data/
      - ./kibana/config/:/opt/kibana/config/
